"use client";

import { useEffect, useState } from "react";
interface Rental { id: string; rentalNo: string; total: number; amountPaid: number; status: string; customerId?: { name: string } }

export default function PaymentsPage() {
  const [rentals, setRentals] = useState<Rental[]>([]); const [error, setError] = useState("");
  const load = async () => { try { const response = await fetch("/api/car-rental/rentals?limit=100", { credentials: "include" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load payment balances"); setRentals(data.rentals || []); } catch (e: unknown) { setError(e instanceof Error ? e.message : "Unable to load payment balances"); } };
  useEffect(() => { void load(); }, []);
  const pay = async (rental: Rental) => { const raw = prompt(`Payment amount for ${rental.rentalNo}`, String(Math.max(0, rental.total - rental.amountPaid))); if (!raw) return; const amount = Number(raw); if (!Number.isFinite(amount) || amount <= 0) return; const response = await fetch("/api/car-rental/payments", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rentalId: rental.id, amount, method: "CASH" }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); setError(data.error || "Unable to record payment"); return; } await load(); };
  return <div><h2 className="text-2xl font-extrabold text-slate-900">Rental Payments</h2><p className="text-slate-500 text-sm mb-6">Collect balances and keep rental contracts reconciled.</p>{error && <div className="mb-4 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm">{error}</div>}<div className="bg-white border border-slate-200 rounded-xl overflow-x-auto"><table className="w-full min-w-[600px]"><thead><tr className="bg-slate-50 border-b border-slate-200"><th className="text-left px-4 py-3 text-xs uppercase text-slate-500">Rental</th><th className="text-left px-4 py-3 text-xs uppercase text-slate-500">Customer</th><th className="text-right px-4 py-3 text-xs uppercase text-slate-500">Total</th><th className="text-right px-4 py-3 text-xs uppercase text-slate-500">Paid</th><th className="text-right px-4 py-3 text-xs uppercase text-slate-500">Balance</th><th /></tr></thead><tbody>{rentals.map((rental) => <tr key={rental.id} className="border-b border-slate-100"><td className="px-4 py-3 text-sm font-semibold">{rental.rentalNo}<div className="text-xs text-slate-400">{rental.status}</div></td><td className="px-4 py-3 text-sm">{rental.customerId?.name || "-"}</td><td className="px-4 py-3 text-right text-sm">PKR {rental.total.toLocaleString()}</td><td className="px-4 py-3 text-right text-sm">PKR {rental.amountPaid.toLocaleString()}</td><td className="px-4 py-3 text-right font-semibold">PKR {Math.max(0, rental.total - rental.amountPaid).toLocaleString()}</td><td className="px-4 py-3 text-right">{rental.total > rental.amountPaid && rental.status !== "CANCELLED" && <button onClick={() => pay(rental)} className="text-xs text-blue-600 font-semibold bg-transparent border-none cursor-pointer">Record payment</button>}</td></tr>)}</tbody></table></div></div>;
}
